<a href="https://colab.research.google.com/github/gzanellato-ia/03-MAIR-GZ-publico/blob/master/Aprendizaje_Supervisado/limpieza_apr_supervisado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Normalización

In [19]:
from sklearn import preprocessing
import numpy as np

# Carga de datos.
X_train = np.array([[ 1., -1., 2.],
                    [ 2., 0., 0.],
                    [ 0., 1., -1.]])

# Limpieza de datos: normalización.
normalizer = preprocessing.MinMaxScaler()           # MinMaxScaler es una clase. Creamos el objeto normalizer
X_train_norm = normalizer.fit_transform(X_train)    # fit: método de Scikit-Learn, crea un modelo a partir de datos
                                                    # transform: toma un modelo y lo aplica a datos
                                                    # fit_transform: aplico el modelo a los mismos datos con el que lo creamos
# Salida de resultados.
print(X_train_norm)


[[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]


In [20]:
# probamos otra función, Normalizer

X_train_norm = preprocessing.normalize(X_train, axis=0, norm='max')     # ojo no da los mismos resultados !!!!!

# Salida de resultados.
print(X_train_norm)


[[ 0.5 -1.   1. ]
 [ 1.   0.   0. ]
 [ 0.   1.  -0.5]]


# Estandarización

In [21]:
from sklearn import preprocessing
import numpy as np

# Carga de datos.
X_train = np.array([[ 1., -1., 2.],
                    [ 2., 0., 0.],
                    [ 0., 1., -1.]])

# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()       # preprocessing:  paquete
                                                    # StandardScaler: clase
                                                    # standardizer:   objeto de la clase StandardScaler
X_train_std = standardizer.fit_transform(X_train)
                                                    # fit_transform:  método                                                    

# Salida de resultados.
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [11]:
# Veamos el atributo 1:
import math
Media = (1+2+0)/3
Desviacion_tipica = math.sqrt(((1-Media)**2+(2-Media)**2+(0-Media)**2)/3)
print('elemento_1 =', (1-Media)/Desviacion_tipica)
print('elemento_2 =', (2-Media)/Desviacion_tipica)
print('elemento_3 =', (0-Media)/Desviacion_tipica)

elemento_1 = 0.0
elemento_2 = 1.224744871391589
elemento_3 = -1.224744871391589
